### ISSUE TITLE
Not reading currently set temp from Tado

### ISSUE THREAD

**Issue by jadomski** [ckuburlis/homebridge-tado#14]
Setting the temperature works wonderful (although I had to remove the swing command per issue #5).

When changing the settings on the Tado unit itself, or via the Tado app, HomeBridge is not reading this change, giving inaccurate information to HomeKit enabled apps and devices.

To clarify, this is just the mode and temperature which the Tado is currently set to. HomeBridge  does read the current room temperature and humidity just fine.

**Comment by nitaybz** [comment]
@iJaffa Updating to the last version + updating the config file should solve the problem

**Comment by jadomski** [comment]
Works great now, thanks!
