### ISSUE TITLE
new Api

### ISSUE THREAD

**Issue by morilm** [ckuburlis/homebridge-tado#19]
Hi all,

Seems Tado has released a new Api with change the authentication process.

http://blog.scphillips.com/posts/2017/01/the-tado-api-v2/

Should it be possible to update the brigde?

Thanks
Miguel

**Comment by nitaybz** [comment]
we are already using v2 api with success authenticating through the url (GET).
if issues will occur it will be changed.
as for now it doesn't seem to affect anything

**Comment by morilm** [comment]
Yes. You are right. I was not using the latest index.js so it was not woking but after updating it everything seems to work.  Thanks for the support.

Next steps on the development could be around setting the TADO in the different ways from Homekit (heater, cooler and termination).

**Comment by nitaybz** [comment]
It's already support that feature... but only with AC, my air conditioner support both heat and cool, and I don't have the Tado Heater/thermostat so I can't implement those.

But the plugin now do support moving around from heating/cooling state of the aircon or just setting it to auto which than makes it to Tado auto mode.

Let me know  if I answered correctly to your question or if I have another way to help.
