### ISSUE TITLE
Command only sent with 'active until ended by a user' state

### ISSUE THREAD

**Issue by jadomski** [ckuburlis/homebridge-tado#25]
When the command is sent with this variable, scheduled changes in the tado app don't take effect.

Simply changing the mode being set from MANUAL to TADO_MODE fixes this issue:

```
        "termination": {
            "type": "TADO_MODE"
        },
```

Alternatively, this could be added to the config file to allow users to change this themselves.

_(It wouldn't be a big problem, except that automation only works for the main HomeKit user, so any additional users in a household don't get these triggers when using HomeKit and need to rely on the tado app for them)_

**Comment by nitaybz** [comment]
there is something in your claim... I will work on a fix and will let you choose with which mode you want the command to be sent

**Comment by nitaybz** [comment]
try install from here:
`sudo npm install -g https://github.com/ckuburlis/homebridge-tado.git#tadoModes`

and add this to your config: 
`"tadoMode": "TADO_MODE"`

let me know if it works so I'll merge it into master

**Comment by jadomski** [comment]
It work in Cool and Heat modes, but not in Off and Auto modes

**Comment by nitaybz** [comment]
try again... I fixed the off mode, but the auto mode is set to remove the manual control. so it should be changing to your tado modes anyway.

**Comment by jadomski** [comment]
Great, it's now working correctly for Cool, Heat, and Off modes. The Auto mode is not working right though...

When I set it to Auto mode now, the Home app shows that the temperature is set to 16º in Auto mode, but the Tado app shows that the control has been released to the tado schedule. Shouldn't it be putting the tado into Auto mode instead?

**Comment by nitaybz** [comment]
I had a bit of a problem here... since the Auto mode is not sending any temperature with it, and homekit must have temperature for any mode, while it gets "null" it automatically set it to the lowest value. if we wanted to get the correct auto temperature we would need to call the get temperature again after setting the Auto mode and that created a weird loop that I couldn't fix.

With that said, it doesn't effect anything, the 16 degrees you see it's only in the home app while your tado is set correctly to the right temperature set on your tado app.
after setting the auto mode, if you will leave the app and open it again, you will see the correct state that your device is on.

if someone has a suggestions on how to solve that I'm open to hear, but for now it does work well so I'm ok with it.

**Comment by nitaybz** [comment]
I can set it to show the last temperature that has been used in home app but it will still not reflect your auto setting temperature.

**Comment by jadomski** [comment]
I see - so where exactly does the auto temperature value come from?

**Comment by nitaybz** [comment]
if you're talking about the 16 degrees it's because it just show the lowest value, but if you're referring to when you reopen the app it takes it from the tado, cause when the home app is open it calls the get state and get temperature commands

**Comment by jadomski** [comment]
Sorry, I mean what option gets sent to the Tado unit when Auto is selected?

**Comment by nitaybz** [comment]
nothing. it just remove the manual control. so your tado auto mode will start rolling.

**Comment by jadomski** [comment]
Ah okay, I guess that works if there is no way to send the Auto command using the tado API

**Comment by nitaybz** [comment]
this is the way to send the Tado auto command.... I'm doing some more changes now hopefully the auto mode will look better in home app

**Comment by nitaybz** [comment]
ok now you can actually see in home app if your AC is on AUTO mode or Manual.

while it's on manual mode you'll see an orange(Heat) or blue(Cool) circle around the room temperature and the status will show: "Heating to..." or "Cooling to...".

when it's on auto mode you'll see a green circle around the room temperature and the status will show: "Heat to..." or "Cool to..."

also I made it so when you change to auto mode the temperature will not change in home app, it will just stay the same.

hope it make everything more clearer.

**Comment by jadomski** [comment]
That makes sense, I didn't realise that's how the tado API works. Thanks, your work is great - I'll update when I get home
