### ISSUE TITLE
Fan Speed Options

### ISSUE THREAD

**Issue by sifield** [ckuburlis/homebridge-tado#27]
Thanks for your work, I loaded and with little fuss it's working perfectly. Just a quick question, I assume the config only allows for one fan state?, I set mine to auto which is ok, however wanted to check that I couldn't configure to give me speed options in the app. Thanks

**Comment by nitaybz** [comment]
unfortunately home app does not support this function. this plugin is built on the thermostat accessory which support only state and temperature (can read the current humidity as well).
therefor, you need to preset your desire state of the fan and the swing so the command sent to tado will be complete. if (and i don't believe it will happen) an option like that will be available in homekit I'll update the plugin as well
