### ISSUE TITLE
get HomeID

### ISSUE THREAD

**Issue by StefanMeGit** [ckuburlis/homebridge-tado#28]
Cant get the HomeID by the old API... is there any other chance?

I can login on https://my.tado.com but with `https://my.tado.com/mobile/1.4/getCurrentState?username=MYEMAIL@gmail.com&password=MYPASSWORD`

```{"errors":[{"code":"unauthorized","title":"Bad credentials"}]}```

**Comment by morilm** [comment]
StefanMeGit..  I was able to get it following the instructions on this page

http://blog.scphillips.com/posts/2017/01/the-tado-api-v2/

Maybe there is an easy way using the old API without the token but I was not able to find it

**Comment by nitaybz** [comment]
Go to tado web page and login, than you can use the inspect option in chrome browser, go to the network tab and check one of the 'state' calls, inside that call you would definitely see the homeID, see the covered red part:
![image](https://cloud.githubusercontent.com/assets/16838394/22567538/045876c6-e999-11e6-809a-efefc4a11a7a.png)

**Comment by StefanMeGit** [comment]
Works pefectly fine! Thanks!!
