### ISSUE TITLE
Turn off via Siri?

### ISSUE THREAD

**Issue by peterchs** [ckuburlis/homebridge-tado#3]
I've forked this for heating, we could probably write a switch to work out between AC and heating and change the json payloads appropriately, but I've just forked it to begin with..

So its working great for me, thanks just really had to alter the json requests.

1 thing is how to get Siri to turn off the AC / heating?  If I use the MyTouchHome app to turn it off it works fine but I can't get Siri to trigger it :(  Any ideas?  Can you turn off from Siri?

Cheers,
Peter

**Comment by peterchs** [comment]
Fixed by adding a characteristic.on - see my fork..

**Comment by ckuburlis** [comment]
Thank you! Hadn't figured out how to do that. 👍
