### ISSUE TITLE
Can read temperature but can't control AC

### ISSUE THREAD

**Issue by jetmcquack** [ckuburlis/homebridge-tado#34]
I have installed the plugin and it seems to work quite well, but i can't control anything. I can read all my ACs, (i have 3) and it also detect if i turn them on/off via the taco app, but i can't tell it to turn on off from home kit. 
I don't know what i can do...
can you help me? 

this is my configuration for one of the ACs

"accessories": [
    {
      "accessory": "TADO",
      "name": "Aria Condizionata Sala",
      "homeID": 42178,
      "maxValue": 30,
      "minValue": 16,
      "zone": 10,
      "username": "XXXXXXXX@gmail.com",
      "password": "XXXXXXXX",
      "useFanSpeed": "AUTO",
      "useSwing": false,
      "tadoMode": "MANUAL",
      "useFahrenheit": false
    },

**Comment by nitaybz** [comment]
did you install it from the git directly?
`sudo npm install -g https://github.com/ckuburlis/homebridge-tado.git`

Also, make sure your FanSpeed  & Swing options are according to your AC capabilities in Tado app. for example, If there is possibility for you to set the Swing, you MUST choose the right state for the command, either "ON" or "OFF". otherwise, if this capability is not available you MUST choose false.

**Comment by jetmcquack** [comment]
Hi i have played a little with the configuration and i found out that even if i set different zone numbers (i have 10, heating included) the datas are always showed only from the zone 1 (AC).
I have found the correct numbers using API v2 and i will paste here for your informations.
One thing to notice is about firmware versions. I have two types for my AC. The oldest one is the one with is causing this behaviour. 

Have you tested the plugin with more than 1 zone?

[
   {
      "id":4,
      "name":"Via Scarpa",
      "type":"HEATING",
      "dateCreated":"2016-09-09T09:53:48.959Z",
      "deviceTypes":[
         "RU01"
      ],
      "devices":[
         {
            "deviceType":"RU01",
            "serialNo":"RU1601FT01052176385536",
            "shortSerialNo":"RU2176385536",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:17:04.429Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "duties":[
               "ZONE_UI",
               "CIRCUIT_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":true,
      "supportsDazzle":true,
      "dazzleEnabled":true
   },
   {
      "id":5,
      "name":"Rispostiglio",
      "type":"HEATING",
      "dateCreated":"2016-12-09T16:58:11.041Z",
      "deviceTypes":[
         "VA01"
      ],
      "devices":[
         {
            "deviceType":"VA01",
            "serialNo":"VA1132266496",
            "shortSerialNo":"VA1132266496",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:19:28.920Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "mountingState":{
               "value":"CALIBRATED",
               "timestamp":"2017-01-10T19:11:50.993Z"
            },
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":true,
      "dazzleEnabled":true
   },
   {
      "id":6,
      "name":"Bagno Piccolo",
      "type":"HEATING",
      "dateCreated":"2016-12-09T17:45:53.282Z",
      "deviceTypes":[
         "VA01"
      ],
      "devices":[
         {
            "deviceType":"VA01",
            "serialNo":"VA0981337088",
            "shortSerialNo":"VA0981337088",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:30:36.744Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "mountingState":{
               "value":"CALIBRATED",
               "timestamp":"2017-01-10T22:47:37.136Z"
            },
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":true,
      "dazzleEnabled":true
   },
   {
      "id":7,
      "name":"Salotto",
      "type":"HEATING",
      "dateCreated":"2016-12-09T20:45:21.715Z",
      "deviceTypes":[
         "VA01",
         "VA01",
         "VA01"
      ],
      "devices":[
         {
            "deviceType":"VA01",
            "serialNo":"VA0143131648",
            "shortSerialNo":"VA0143131648",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:33:57.979Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "mountingState":{
               "value":"CALIBRATED",
               "timestamp":"2017-01-10T18:16:04.973Z"
            },
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER"
            ]
         },
         {
            "deviceType":"VA01",
            "serialNo":"VA2307195904",
            "shortSerialNo":"VA2307195904",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:29:40.780Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "mountingState":{
               "value":"CALIBRATION_FAILED",
               "timestamp":"2017-03-10T18:34:02.300Z"
            },
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         },
         {
            "deviceType":"VA01",
            "serialNo":"VA3564569600",
            "shortSerialNo":"VA3564569600",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:34:10.360Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "mountingState":{
               "value":"CALIBRATED",
               "timestamp":"2017-01-10T21:07:17.674Z"
            },
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":true,
      "dazzleEnabled":true
   },
   {
      "id":8,
      "name":"Bagno Grande",
      "type":"HEATING",
      "dateCreated":"2016-12-10T16:16:15.442Z",
      "deviceTypes":[
         "VA01"
      ],
      "devices":[
         {
            "deviceType":"VA01",
            "serialNo":"VA0796066816",
            "shortSerialNo":"VA0796066816",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:30:02.983Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "mountingState":{
               "value":"CALIBRATED",
               "timestamp":"2017-02-24T15:34:25.225Z"
            },
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":true,
      "dazzleEnabled":true
   },
   {
      "id":9,
      "name":"Camera",
      "type":"HEATING",
      "dateCreated":"2016-12-10T16:25:00.630Z",
      "deviceTypes":[
         "VA01"
      ],
      "devices":[
         {
            "deviceType":"VA01",
            "serialNo":"VA0544015360",
            "shortSerialNo":"VA0544015360",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:33:44.211Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "mountingState":{
               "value":"CALIBRATED",
               "timestamp":"2017-01-10T20:38:55.539Z"
            },
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":true,
      "dazzleEnabled":true
   },
   {
      "id":10,
      "name":"Studio",
      "type":"HEATING",
      "dateCreated":"2016-12-11T20:10:04.991Z",
      "deviceTypes":[
         "VA01"
      ],
      "devices":[
         {
            "deviceType":"VA01",
            "serialNo":"VA3196388352",
            "shortSerialNo":"VA3196388352",
            "currentFwVersion":"36.15",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:34:31.569Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT",
                  "IDENTIFY"
               ]
            },
            "mountingState":{
               "value":"CALIBRATED",
               "timestamp":"2017-01-10T11:18:28.532Z"
            },
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":true,
      "dazzleEnabled":true
   },
   {
      "id":1,
      "name":"Salotto",
      "type":"AIR_CONDITIONING",
      "dateCreated":"2016-02-12T06:44:48.982Z",
      "deviceTypes":[
         "WR01"
      ],
      "devices":[
         {
            "deviceType":"WR01",
            "serialNo":"WR1506FT01001359806720",
            "shortSerialNo":"WR1359806720",
            "currentFwVersion":"22.13",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:34:27.772Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT"
               ]
            },
            "accessPointWiFi":{
               "ssid":"tado6720"
            },
            "commandTableUploadState":"FINISHED",
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":false,
      "dazzleEnabled":true
   },
   {
      "id":2,
      "name":"Studio",
      "type":"AIR_CONDITIONING",
      "dateCreated":"2016-07-12T05:40:29.282Z",
      "deviceTypes":[
         "WR01"
      ],
      "devices":[
         {
            "deviceType":"WR01",
            "serialNo":"WR4060413952",
            "shortSerialNo":"WR4060413952",
            "currentFwVersion":"26.1",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:34:37.976Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT"
               ]
            },
            "accessPointWiFi":{
               "ssid":"tado3952"
            },
            "commandTableUploadState":"FINISHED",
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":false,
      "dazzleEnabled":true
   },
   {
      "id":3,
      "name":"Camera",
      "type":"AIR_CONDITIONING",
      "dateCreated":"2016-07-26T21:16:35.772Z",
      "deviceTypes":[
         "WR01"
      ],
      "devices":[
         {
            "deviceType":"WR01",
            "serialNo":"WR3154444288",
            "shortSerialNo":"WR3154444288",
            "currentFwVersion":"26.1",
            "connectionState":{
               "value":true,
               "timestamp":"2017-03-13T06:33:56.370Z"
            },
            "characteristics":{
               "capabilities":[
                  "INSIDE_TEMPERATURE_MEASUREMENT"
               ]
            },
            "accessPointWiFi":{
               "ssid":"tado4288"
            },
            "commandTableUploadState":"FINISHED",
            "duties":[
               "ZONE_UI",
               "ZONE_DRIVER",
               "ZONE_LEADER"
            ]
         }
      ],
      "reportAvailable":false,
      "supportsDazzle":false,
      "dazzleEnabled":true
   }
]

**Comment by jetmcquack** [comment]
Ok i figured out that i had a different version installed.
Sorry for bothering you!
BTW can you update the default version on NPM? i thought to have installed it via command line correctly from GIT but it seems the commands listed on NPM to do this are different,

thanks anyway,

Francesco

**Comment by nitaybz** [comment]
the owner of this repo is not updating anymore and he gave me the ability to change and update the code, but i can't update it on npm,
therefor I've created a seperate plugin that is updated in npm called homebridge-tado-ac
