### ISSUE TITLE
Tado causes homebridge to fail

### ISSUE THREAD

**Issue by Pltnorwich** [ckuburlis/homebridge-tado#38]
Hi,
The plugin sometimes causes homebridge to fail after a reboot. so i remove homebridge from the IOS Home app, go to re add (i have a door lock and the Tado in homebridge). 
1)Homebridge adds ok
2)door lock adds ok
3)Tado fails, communication error

This is the error from the file...
[4/19/2017, 4:33:27 PM] [Tado] Getting room temperature
[4/19/2017, 4:33:27 PM] [Tado] getting temperature display units = 0
[4/19/2017, 4:33:27 PM] [Tado] Getting target state
[4/19/2017, 4:33:28 PM] [Tado] Target temperature is 21ºC
[4/19/2017, 4:33:28 PM] [Tado] Getting current state
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND my.tado.com my.tado.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

The only way I cleared this before was to start from scratch and reinstall everything - not ideal. Currently the plugin is deleted from my son file to stop it loading so I can still use the lock. Any help would be grateful. Oh the thermostat has communication as i can adjust the temperature from my phone and the boiler will fire.

Thanks

Phil

**Comment by nitaybz** [comment]
are you using the latest version from the git? cause the npm version is not updated...
also, are you using this plugin for Tado AC?

**Comment by Pltnorwich** [comment]
Hi, no I'm using tado heating from npm, it's version 0.1.1

All the ones on GitHub are for AC only I think....?

Sent from my iPhone

On 5 May 2017, at 00:24, nitaybz <notifications@github.com<mailto:notifications@github.com>> wrote:


are you using the latest version from the git? cause the npm version is not updated...
also, are you using this plugin for Tado AC?

**Comment by nitaybz** [comment]
Taro heating is not supported by this plugin. To be honest, the only plugin that does support it is homeridge-tadong and it hasn't been updated for a while now...
Anyway, you are looking for support on the wrong place

**Comment by Pltnorwich** [comment]
Hi Nitaybz,

There was no where on the npm site to bring this issue up and thought theses must function pretty similar.
The homebridge-tadoheating works most the time, just every now and then it shows that connection issue.

I have tried looking for another plugin but can not find one to see if it's any better.


Sent from my iPhone

On 5 May 2017, at 09:25, nitaybz <notifications@github.com<mailto:notifications@github.com>> wrote:

Taro heating is not supported by this plugin. To be honest, the only plugin that does support it is homeridge-tadong and it hasn't been updated for a while now...
Anyway, you are looking for support on the wrong place

**Comment by nitaybz** [comment]
The tado-heating plugin is using the old API call. I updated this one to the new one and I only have the Tado AC device, that's why I only updated this plugin, I have no way of working with the heating device, sorry...

I hope someone will pick this up from here and update the plugin to support the heater

**Comment by rafacampoamor** [comment]
Hi, 

The plugin was working just fine for like 24h, but today it got this error repteadly before crashing homebridge

TypeError: Cannot read property 'mode' of undefined
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-tado/index.js:157:64)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Can you help me?

**Comment by nitaybz** [comment]
@rafacampoamor does it always happen or occasionally?
Tado recently changed it's api login request... I did some modifications to my own fork - [homebridge-tado-ac](https://github.com/nitaybz/homebridge-tado-ac) in order to work with the new api version.
please try to install with this command:
`sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac#test`

this version contains a lot of logs to debug in case it's not working for you.
give it a shot and let me know how it reacts.

**Comment by Pltnorwich** [comment]
Hi Nitabz,

I think the poster, and me before have the heating not the ac Tado. is your AC one compatible? or would you be able to update a Tado Heating plugin with the new API?

For me the Tado plugin kept crashing the home bridge roughly every 24hrs, as soon as i removed it and only ran home bridge and Away server its been fine - so definitely a Tado heating plugin issue.


On 12 Jun 2017, at 21:10, nitaybz <notifications@github.com<mailto:notifications@github.com>> wrote:


does it always happen or occasionally?
Tado recently changed it's api login request... I did some modifications to my own fork - homebridge-tado-ac<https://github.com/nitaybz/homebridge-tado-ac> in order to work with the new api version.
please try to install with this command:
sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac#test

this version contains a lot of logs to debug in case it's not working for you.
give it a shot and let me know how it reacts.

**Comment by rafacampoamor** [comment]
I think it's related with the get current temperature call. Homebridge
keeps working until I open control center or the Home app, and it ask for
data and Homebridge crashes. This evening I'll test your beta and let you
know

Thank you


De: nitaybz <notifications@github.com> <notifications@github.com>
Responder: ckuburlis/homebridge-tado
<reply@reply.github.com>
<reply@reply.github.com>
Fecha: 12 de junio de 2017 at 22:10:46
Para: ckuburlis/homebridge-tado <homebridge-tado@noreply.github.com>
<homebridge-tado@noreply.github.com>
CC: rafacampoamor <rafacampoamor@gmail.com> <rafacampoamor@gmail.com>,
Comment <comment@noreply.github.com> <comment@noreply.github.com>
Asunto:  Re: [ckuburlis/homebridge-tado] Tado causes homebridge to fail
(#38)

does it always happen or occasionally?

**Comment by nitaybz** [comment]
@Pltnorwich I've seen a new plugin around that goes by the name "tadowater"
I think this one handles with the tado heating.

**Comment by taimurasad** [comment]
I was having the exact same problem. Looks like ckuburlis's version needs an update cause uninstalling that and then installing Nitabz's version did the trick for me. This is what I did:

sudo npm uninstall homebridge-tado
rm -rf .homebridge/persist/
sudo npm install -g https://github.com/nitaybz/homebridge-tado-ac#test
cd .homebridge
ls
cd
homebridge

and everything works again!

I have one question for Nitabz though, the test version (homebridge-tado-ac#test) that I have installed, would it continue working in future or do I need to switch to main (homebridge-tado-ac) version of his? Hope he continue to update and support it!

**Comment by nitaybz** [comment]
@taimurasad
the owner of this plugin "homebridge-tado", is no longer supporting this plugin, even all the last updates on this plugin I did. but because I couldn't update on npm I decided to create a new plugin - "homebridge-tado-ac". the new plugin will be updated & supported in the future since I myself have 3 Tado AC devices that I need to maintain.

soon I will clean the test version and merge it in to my main "homebridge-tado-ac" plugin.

**Comment by nitaybz** [comment]
the new (clean) version is updated...
feel free to install from npm:
`sudo npm install -g homebridge-tado-ac`

**Comment by taimurasad** [comment]
@nitaybz do I need to uninstall homebridge-tado-ac#test first and then install homebridge-tado-ac version? Thanks!

**Comment by nitaybz** [comment]
no... you can just install the new one...
make sure you don't have the homebridge-tado version installed

**Comment by taimurasad** [comment]
@nitaybz I see so basically it will simply overwrite the test version?

**Comment by nitaybz** [comment]
exactly!

**Comment by ckuburlis** [comment]
@nitaybz not sure if it helps but I think I’ve given you access to make changes on npm (guessing you have the same username there as you do here)

**Comment by Pltnorwich** [comment]
@nitaybz,
I'm guessing you are not, or don't fancy writing a plugin for Tado heating, as you have done for the AC.
I'll have a look at that hot water one you mentioned.

Sent from my iPhone

On 13 Jun 2017, at 09:40, Chris <notifications@github.com<mailto:notifications@github.com>> wrote:


@nitaybz<https://github.com/nitaybz> not sure if it helps but I think I’ve given you access to make changes on npm (guessing you have the same username there as you do here)

**Comment by nitaybz** [comment]
I don't have the device, which will be a bit hard to test

**Comment by nitaybz** [comment]
#29
closing, further discussion will be on my plugin
