### ISSUE TITLE
Tado Heating Auto mode displaying 30 deg

### ISSUE THREAD

**Issue by JangoBritt** [ckuburlis/homebridge-tado#6]
I've just installed the tadoheating fork, because my brand new v3 Tado shipped without the HomeKit bridge (delayed due to... whatever).

When I set the mode to Auto, it shows up as "heating to 30 deg" Holy hell that's a shock. lol

I know it's not actually heating to 30 deg, because Auto mode is the only mode that switches the tado web interface back into presence detection, but wouldn't it be better if auto mode would return the Setting:temperature:celcius from the state API, rather than the hardcoded maxValue in the script?

**Comment by nitaybz** [comment]
@JangoBritt in the new version of homebridge-Tado that kind of support is available.
Unfortunately I can't help you with that fork cause it's not in my control.

you can try your luck here:
https://github.com/peteakalad/homebridge-tadoHeating
