### ISSUE TITLE
Hard-coded min/Max values?

### ISSUE THREAD

**Issue by JangoBritt** [ckuburlis/homebridge-tado#7]
Just wondering why the minValue, maxValue, and minStep temperature values are hard-coded in the script?

Would it not be a good idea to allow that to be configured in the config.json parameters? otherwise.... how would I use homekit to set my temperature to 17.3 deg overnight?

**Comment by nitaybz** [comment]
@JangoBritt Updating to the last version + updating the config file should solve the problem
