### ISSUE TITLE
Multiple zones

### ISSUE THREAD

**Issue by leonbarrett** [ckuburlis/homebridge-tado#9]
Hi, 

How do you add support for multiple zones? i.e I have two thermostats in my setup.

Thanks

**Comment by morilm** [comment]
Is working.  Ensure you have the last index.js (not the one that it's installed by default) and update the configuration file to include each zone

**Comment by leonbarrett** [comment]
Hi, could you provide an example config file please? Thanks

**Comment by morilm** [comment]
config file to control 2 zones in the same home.  Ensure the index.js is properlly updated.

{
    "bridge": {
        "name": "Homexxx",
        "username": "CC:11:11:E3:CE:12",
        "port": 518323,
        "pin": "011-11-111"
    },

    "description": "Config",

    "accessories": [
    {
      "accessory": "TADO",
      "name": "Salon",
      "homeID": "xxxxx",
      "maxValue": 27,
      "minValue": 18,
      "zone": 1,
      "username": "xxxx",
      "password": "xxxxx",
      "useFanSpeed": "LOW",
      "useSwing": false,
      "useFahrenheit": false
    },    {
          "accessory": "TADO",
          "name": "Dormitorio",
          "homeID": "xxxxx",
          "maxValue": 27,
          "minValue": 18,
          "zone": 2,
          "username": "xxxxxxx",
          "password": "xxxxxxx",
          "useFanSpeed": "LOW",
          "useSwing": false,
          "useFahrenheit": false
        }
  ]
}

**Comment by nitaybz** [comment]
@leonbarrett # Please review the READ.md file, it is updated now for better understanding of the configuration.
